### ISSUE TITLE
Tests for NDMG

### ISSUE THREAD

**Issue by ebridge2** [neurodata/m2g#180]
Add testing suite for ndmg pipeline that is travis-compliant (or not, depends on the size of the test cases).

testing suite should be command line executable.

travis executable scripts:
- test BIDs utilities
    - make dummy files that are named properly according to bids spec, and are named to mirror the test subjects subset; however, the files will all be empty. this will facilitate just checking that the BIDs parsing works, despite the fact that testing on a full BIDs dataset would not be executable by travis.
- test that files are produced where we expect them to be (QA, as well as all other derivatives)
- test basic properties of derivatives: fMRI connectomes are dense; dMRI are sparse; dMRI contain off-diagonal edges.
- make dummy data for fMRI nusiance correction. add low pass signal, add linear, quadratic, and scalar drift. add gaussian noise. verify that the nuisance correction recovers something close to zero signal.
- verify that fMRI timeseries are `n x t` for `t` timesteps.
- 

non-travis executable scripts (since this test case will be too big/complex, and travis is memory/compute limited):
- accepts a set of AWS credentials.
- identify a subset of subjects to use for testing. This can supplement our existing "test batch" of subjects, available in the aws bucket at `aws s3 cp --no-sign-request s3://mrneurodata/bids_test.tar.gz ./`
- modify so that the test subjects are stored in a BIDs format on AWS. this will facilitate execution of the cloud container.
- launch a job, and check in the background every `n` seconds for successful completion of the job. The NDMG aws utility already has a function for doing this, so it will just be a matter of setting this up to run on its own node.
    - verify after the script reports "completed" that you can query for the data on aws, that it exists, and that the proper files are produced.
- use DICE overlap with brain-extracted registered brain, to confirm that the DICE scores exceed a particular threshold (registration success)
- execute ndmg_bids with dmri and fmri on testing data, confirm all derivatives produced successfully.
- confirm basic known properties about the produced connectomes: dMRI separated left/right hemisphere after `ASE`, fMRI has homotopic connectivity > heterotopic connectivity.

**Comment by gkiar** [comment]
> Add testing suite for ndmg pipeline that is travis-compliant (or not, depends on the size of the test cases).

It is definitely imperative that the tests be run on push, whether through travis or circle CI.

> testing suite should be command line executable.

I'm not sure what you mean here, but if you mean anything other than `pytest`, I disagree. It's important to be in Python and not clutter the package executable name space, that way we get to make assertions about data values, see lines of failure, and intercept the execution to evaluate small components independently.

> - test BIDs utilities
>   - make dummy files that are named properly according to bids spec, and are named to mirror the test subjects subset; however, the files will all be empty. this will facilitate just checking that the BIDs parsing works, despite the fact that testing on a full BIDs dataset would not be executable by travis.

We should just download a real BIDS dataset instead - there are many publicly available - and process it for 1 subject.

> - test that files are produced where we expect them to be (QA, as well as all other derivatives)
> - test basic properties of derivatives: fMRI connectomes are dense; dMRI are sparse; dMRI contain off-diagonal edges.
> -make dummy data for fMRI nusiance correction. add low pass signal, add linear, quadratic, and scalar drift. add gaussian noise. verify that the nuisance correction recovers something close to zero signal.
> - verify that fMRI timeseries are n x t for t timesteps.

For many of these you should just store the test result somewhere, process the data, and assert that the two files are identical. This breaks in stages when you change actual pipeline logic, but when it's cleaning things up or refactoring the data should be unchanged.

> non-travis executable scripts (since this test case will be too big/complex, and travis is memory/compute limited):

The testing script for the ndmg BIDS app runs two sessions through the DWI pipeline, on Circle CI. I don't think any of the tests below make much sense, and certainly not to be run outside of any CI package. To test the pipeline, you should run the pipeline on data somewhere you trust, compute hashes of the results, store those, and compare the hashes of the outputs to the outputs produced during execution on test time. These should be 100% automatic, not require any credentials for a resource, and do more than a subjective comparison. For testing cloud functionality, you should look into `moto`, a `boto3` mock-client for exactly this purpose.
